name: "Pest"

on: [push]

jobs:
  pest:
    strategy:
      matrix:
        php: ["8.2"]
        laravel: ["^12.0"]
      fail-fast: false

    name: "Pest"

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - uses: nathanheffley/laravel-phpunit-action@master
