name: "Pest"

on: [push]

jobs:
  pest:
    strategy:
      matrix:
        php: ["8.2"]
        laravel: ["^12.0"]
      fail-fast: false

    name: "Pest"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: ''

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "dom, curl, libxml, mbstring, zip, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: "Check Composer configuration"
        run: "composer validate"

      - name: "Install highest dependencies from composer.json"
        run: "composer update --with='laravel/framework:${{ matrix.laravel }}' --no-interaction --no-progress"

      - name: "Check PSR-4 mapping"
        run: "composer dump-autoload --optimize"

      - name: "Run Pest on a sample Laravel application"
        run: |
          version="${{ matrix.laravel }}"
          vendor/bin/pest
